// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/payload.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Unit struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Details              *any.Any `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Unit) Reset()         { *m = Unit{} }
func (m *Unit) String() string { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()    {}
func (*Unit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42bfc414a05e0f3, []int{0}
}

func (m *Unit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Unit.Unmarshal(m, b)
}
func (m *Unit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Unit.Marshal(b, m, deterministic)
}
func (m *Unit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Unit.Merge(m, src)
}
func (m *Unit) XXX_Size() int {
	return xxx_messageInfo_Unit.Size(m)
}
func (m *Unit) XXX_DiscardUnknown() {
	xxx_messageInfo_Unit.DiscardUnknown(m)
}

var xxx_messageInfo_Unit proto.InternalMessageInfo

func (m *Unit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Unit) GetDetails() *any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

type Payload struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Units                []*Unit  `protobuf:"bytes,2,rep,name=units,proto3" json:"units,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42bfc414a05e0f3, []int{1}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Payload) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func init() {
	proto.RegisterType((*Unit)(nil), "pb.Unit")
	proto.RegisterType((*Payload)(nil), "pb.Payload")
}

func init() { proto.RegisterFile("pb/payload.proto", fileDescriptor_f42bfc414a05e0f3) }

var fileDescriptor_f42bfc414a05e0f3 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xcd, 0xc1, 0x0b, 0x82, 0x30,
	0x14, 0x06, 0x70, 0x9c, 0x9a, 0xf1, 0x84, 0x88, 0xe1, 0xc1, 0x3a, 0x84, 0x78, 0xf2, 0xf4, 0x04,
	0xfb, 0x03, 0xa2, 0x0e, 0x9d, 0x63, 0xd0, 0xa5, 0xdb, 0xc6, 0x4c, 0x06, 0x63, 0x1b, 0x35, 0x03,
	0xff, 0xfb, 0xd0, 0xe1, 0xf1, 0x7d, 0xef, 0xe3, 0xf7, 0xc1, 0xde, 0x89, 0xd6, 0xf1, 0x49, 0x5b,
	0x2e, 0xd1, 0x7d, 0xac, 0xb7, 0x94, 0x38, 0x71, 0x3c, 0x0c, 0xd6, 0x0e, 0xba, 0x6f, 0x97, 0x44,
	0x8c, 0xef, 0x96, 0x9b, 0x29, 0xbc, 0xeb, 0x3b, 0x24, 0x4f, 0xa3, 0x3c, 0xdd, 0x01, 0x51, 0xb2,
	0x8c, 0xaa, 0xa8, 0x89, 0x19, 0x51, 0x92, 0x22, 0x64, 0xb2, 0xf7, 0x5c, 0xe9, 0x6f, 0x49, 0xaa,
	0xa8, 0xc9, 0xbb, 0x02, 0x03, 0x82, 0x2b, 0x82, 0x57, 0x33, 0xb1, 0xb5, 0x54, 0x5f, 0x20, 0x7b,
	0x84, 0x5d, 0x5a, 0x40, 0xfa, 0xe3, 0x7a, 0xec, 0x17, 0x2d, 0x65, 0xe1, 0xa0, 0x27, 0x48, 0x47,
	0xa3, 0xfc, 0xcc, 0xc5, 0x4d, 0xde, 0x6d, 0xd1, 0x09, 0x9c, 0x97, 0x59, 0x88, 0x6f, 0xc9, 0x8b,
	0x38, 0x21, 0x36, 0x8b, 0x7e, 0xfe, 0x07, 0x00, 0x00, 0xff, 0xff, 0xba, 0x92, 0x44, 0x2f, 0xc8,
	0x00, 0x00, 0x00,
}
